version: "3.8"
services:
  property-comparison:
    build: .
    container_name: homes-shottsserver
    ports:
      - "3080:3000"
    volumes:
      - /mnt/cache/appdata/property-comparison/data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PUID=99
      - PGID=100
      - TZ=America/Denver
    networks:
      - shottsproxy

networks:
  shottsproxy:
    external: true
